### Lab 04

Labs in general are for you to solve short programming challenges in class. In contrast, homework assignments will involve more challenging and lengthy problems.

Feel free to ask the TAs for help if there is anything you do not understand. The TAs will go through suggested solutions in the last 15 minutes of the lab - typically by solving them in a live demo. **Your midterm exams will be like this, so it is highly beneficial for you to attend these labs**.

The second lab is to gain basic familiarity with handling vectors, matrices and basic linear algebra. 

- You can import any Python standard library module you need
- Do this lab without using the web to search for solutions

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
np.random.seed(123)
m = 10
n = 10
A = np.random.normal(0, 1, (m, n))
b = np.random.normal(0, 1,(n, 1))

**1**.

Perform an LU decomposition to solve $Ax = b$

- Using `lu_factor` and `solve_triangular`
- Using `lu` and `solve_triangular`
- Check that your answer is correct using `np.allclose` in each case

In [3]:
x1 = la.lu_solve(la.lu_factor(A),b)
x1

array([[-14.364331  ],
       [ -3.61578614],
       [  3.44012072],
       [  6.61238896],
       [  1.3593646 ],
       [ -5.20062081],
       [ -0.89588219],
       [ -3.65151504],
       [ -2.04870667],
       [ -6.77130993]])

In [4]:
P,L,U = la.lu(A)
y = la.solve_triangular(L,P.T@b,lower = True)
x2 = la.solve_triangular(U,y)
x2

array([[-14.364331  ],
       [ -3.61578614],
       [  3.44012072],
       [  6.61238896],
       [  1.3593646 ],
       [ -5.20062081],
       [ -0.89588219],
       [ -3.65151504],
       [ -2.04870667],
       [ -6.77130993]])

In [5]:
np.allclose(x1,x2)

True

**2**.

Calculate the Gram matrix $S = A^TA$. Use the same $A$ and $b$ from the previous question. 

- Solve $Sx = b$ using Cholesky decomposition
- Check that your answer is correct using `np.allclose`

In [6]:
S = A.T@A
Q = la.cholesky(S)
y = la.solve_triangular(Q.T,b,lower=True)
x = la.solve(Q,y)
x

array([[-136.71894832],
       [ -33.85176812],
       [  41.84149034],
       [  73.42723076],
       [  12.50311233],
       [ -41.91028953],
       [  -6.01395804],
       [ -30.7294723 ],
       [ -24.21718752],
       [ -68.80957079]])

In [7]:
np.allclose(Q.T@Q@x,b)

True

**3**. 

- Diagonalize the matrix $S$ by finding its eigenvalues and eigenvectors
- Check that your answer is correct using `np.allclose`

In [8]:
lam, vec = la.eig(S)
np.allclose(vec@np.diag(lam)@vec.T,S)

True

**4**. 

- Perform a singular value decomposition (SVD) of the matrix $A$.
- Use the singular values to calculate the $L_\text{Frobenius}$ and $L_2$ norms of $A$
- Check your answers using `la.norm` and `np.allclose`
- Express the eigenvalues of $S$ in terms of the singular values $\sigma$
- Check your answers using `np.allclose`



In [9]:
U,s,V = la.svd(A)

In [11]:
np.allclose(la.norm(A,ord = "fro"),np.sqrt(np.sum(s**2)))

True

In [12]:
np.allclose(la.norm(A,ord = 2),s.max())

True

In [30]:
np.allclose(s**2,lam[::-1].real)

True

**5**.

Suppose a vector $v$ has coordinates $b$ when expressed as a linear combination of the columns of $A$. What are the new coordinates of $v$ when expressed as a linear combination of the (normalized) eigenvectors of $A$?

$Av = b$  
$Q\Lambda Q^{-1}v = b$  
$\rightarrow \Lambda Q^{-1}v = Q^{-1}b$